### PR TITLE
fix: use `dom-align` to position dnd container (#3978)

### LINKED ISSUE #3978: plugin-dnd 配置了 draggingContainer 后，最新代码计算位置仍有偏差
### Describe the bug

之前的issue: #3873  以及相关修改: #3953

当 `draggingContainer` 没有设置 `position` 时(即默认的`position:static`)，这里错误的减掉了`draggingContainer`的偏移；
另外，当 `draggingContainer` 或其它上层容器有滚动条时，也没有正确计算进去

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

无

### Screenshots or Videos

_No response_

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

### Additional context

看了下 [ant-design-vue](https://github.com/vueComponent/ant-design-vue/blob/main/components/vc-align/Align.tsx#L92)，使用的是 [dom-align](https://github.com/yiminghe/dom-align) 库进行对齐计算的，它会处理各层容器的scroll、position等

附上使用`dom-align`修复方案作参考
```ts
export default class MyDndPlugin extends Dnd {
    protected updateGraphPosition(clientX: number, clientY: number) {
        const delta = this.delta!;
        const nodeBBox = this.geometryBBox;
        const padding = this.padding || 5;
        const offset = {
            left: clientX - delta.x - nodeBBox.width / 2 - padding,
            top: clientY - delta.y - nodeBBox.height / 2 - padding,
        };

        if (this.draggingGraph) {
            alignPoint(
                this.container,
                {
                    clientX: offset.left,
                    clientY: offset.top,
                },
                {
                    points: ['tl'],
                },
            );
        }

        // TODO 原组件目前没有使用这个返回值（代码注释掉了）
        // 而 dom-align 又没有返回计算后的top/left值
        // 考虑干掉?
        return offset;
    }
}
```

### PR DESCRIPTION
**Pull request by cyrilluce**
### Description

fix #3978

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: packages/x6-plugin-dnd/src/index.ts [hunk 1]
```diff
@@ -169,35 +170,32 @@ export class Dnd extends View implements Graph.Plugin {
...
+            },
+            {
+                points: ['tl'],
+            },
+        );
     }
 
-    return offset
-  }
+    // TODO 原组件目前没有使用这个返回值（代码注释掉了）
```
Comment (NewByVector) [inline packages/x6-plugin-dnd/src/index.ts:194]: 可以去掉，把这个注释删除吧。

**Review by NewByVector — CHANGES_REQUESTED** [review]

File: packages/x6-plugin-dnd/src/index.ts (hunk 1 above)
Comment (cyrilluce) [reply packages/x6-plugin-dnd/src/index.ts]: OK，因为ts约束，我先把 `originOffset` 属性删除了

**Comment by cyrilluce** [comment]
ci失败了，看起来像是 runner 的问题？

**Review by NewByVector — APPROVED** [review]
