### PR TITLE
fix: scale event parameters always 0

### LINKED ISSUE #4024: 画布scale事件有个bug
### Describe the bug

缩放的中心点(ox,oy)永远都是0.

### Your Example Website or App

https://x6.antv.antgroup.com/examples/node/native-node/#text-block

### Steps to Reproduce the Bug or Issue

```javascript
import { Graph } from '@antv/x6'

const graph = new Graph({
  container: document.getElementById('container'),
  mousewheel:true,
  scaling:{
    min:0.1,
    max:10
  },
  grid: true,
})
graph.on('scale', (e) => {
            console.log(e)
            console.log(textNode)
textNode.prop('attrs/label/text',JSON.stringify(e));
        })

const textNode=graph.addNode({
  x: 160,
  y: 120,
  width: 360,
  height: 120,
  shape: 'text-block',
  text: `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.`,
  attrs: {
    body: {
      fill: '#efdbff',
      stroke: '#9254de',
      rx: 4,
      ry: 4,
    },
  },
})

```
鼠标滚轮转动，查看事件里的数据

### Expected behavior

ox和oy.能正常返回

### Screenshots or Videos

动画

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by q32757468**
### Description
fixed: https://github.com/antvis/X6/issues/4024

### Motivation and Context
无scroll画布时的效果图：
image

带scroll画布时：
image

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: src/graph/transform.ts [hunk 1]
```diff
@@ -90,14 +90,17 @@ export class TransformManager extends Base {
...
-  scale(sx: number, sy: number = sx, ox = 0, oy = 0) {
+  scale(sx: number, sy: number = sx, ox = 0, oy = 0, translate = true) {
     sx = this.clampScale(sx) // eslint-disable-line
     sy = this.clampScale(sy) // eslint-disable-line
 
-    if (ox || oy) {
+    if (translate && (ox || oy)) {
       const ts = this.getTranslation()
-      const tx = ts.tx - ox * (sx - 1)
-      const ty = ts.ty - oy * (sy - 1)
```
Comment (q32757468) [inline src/graph/transform.ts:100]: 原本scale这里的平移逻辑只有在原始缩放为1时才是正确的，如果原始缩放因子不为1就会有问题，但是奇怪的是这里原本的代码逻辑没有被内部任何一个地方消费，同时也导致了没有正确传递缩放点的参数

File: src/graph/transform.ts [hunk 2]
```diff
@@ -90,14 +90,17 @@ export class TransformManager extends Base {
...
+      const scale = this.getScale()
+
+      const tx = ox - (ox - ts.tx) * (sx / scale.sx)
+      const ty = oy - (oy - ts.ty) * (sy / scale.sy)
```
Comment (q32757468) [inline src/graph/transform.ts:102]: 新的平移逻辑是从外层转移过来的，确保平移效果正确

File: src/plugin/scroller/scroller.ts [hunk 3]
```diff
@@ -741,7 +741,7 @@ export class ScrollerImpl extends View<ScrollerImpl.EventArgs> {
     }
 
     this.beforeManipulation()
-    this.graph.transform.scale(sx, sy)
+    this.graph.transform.scale(sx, sy, cx, cy, false)
     this.centerPoint(cx, cy)
```
Comment (q32757468) [inline src/plugin/scroller/scroller.ts:745]: 开启scroll插件后的scale 不需要内置的平移逻辑，由 centerPoint 来提供

**Review by GaoFuhong — APPROVED** [review]
good pr
